# This workflow will install Python dependencies, run lint checks, and tests with Python 3.12
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Set up Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        cd backend
        poetry config virtualenvs.create false
        poetry install --with dev

    - name: Lint
      run: |
        cd backend
        poetry run task lint

    - name: Test
      run: |
        cd backend
        poetry run task test
